In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data.csv")
df.tail()

     Duration  Pulse  Maxpulse  Calories
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [3]:
# Axis = 1 -> x // Axis=0 -> y
df[df.isna().any(axis=1)]

     Duration  Pulse  Maxpulse  Calories
17         45     90       112       NaN
27         60    103       132       NaN
91         45    107       137       NaN
118        60    105       125       NaN
141        60     97       127       NaN

In [4]:
indices = df[df.isna().any(axis=1)].index
indices

Index([17, 27, 91, 118, 141], dtype='int64')

In [5]:
# loc[rows, columns]
df.loc[:, "Duration"]

0      60
1      60
2      60
3      45
4      45
       ..
164    60
165    60
166    60
167    75
168    75
Name: Duration, Length: 169, dtype: int64

In [6]:
df_dropped = df.dropna()

df_dropped.size

656

In [10]:
df_filled = df["Duration"].fillna(130)

df_filled.size

169

In [19]:
[print(x) for x in df]

Duration
Pulse
Maxpulse
Calories

[None, None, None, None]

In [20]:
import numpy as np

In [23]:
arr = np.zeros([3,2])
arr

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [24]:
df.shape

(169, 4)

In [26]:
for i in df.iterrows():
    print(i)

(0, Duration     60.0
Pulse       110.0
Maxpulse    130.0
Calories    409.1
Name: 0, dtype: float64)
(1, Duration     60.0
Pulse       117.0
Maxpulse    145.0
Calories    479.0
Name: 1, dtype: float64)
(2, Duration     60.0
Pulse       103.0
Maxpulse    135.0
Calories    340.0
Name: 2, dtype: float64)
(3, Duration     45.0
Pulse       109.0
Maxpulse    175.0
Calories    282.4
Name: 3, dtype: float64)
(4, Duration     45.0
Pulse       117.0
Maxpulse    148.0
Calories    406.0
Name: 4, dtype: float64)
(5, Duration     60.0
Pulse       102.0
Maxpulse    127.0
Calories    300.0
Name: 5, dtype: float64)
(6, Duration     60.0
Pulse       110.0
Maxpulse    136.0
Calories    374.0
Name: 6, dtype: float64)
(7, Duration     45.0
Pulse       104.0
Maxpulse    134.0
Calories    253.3
Name: 7, dtype: float64)
(8, Duration     30.0
Pulse       109.0
Maxpulse    133.0
Calories    195.1
Name: 8, dtype: float64)
(9, Duration     60.0
Pulse        98.0
Maxpulse    124.0
Calories    269.0
Name: 9, dtype: float64)
(10, Duration     60.0
Pulse       103.0
Maxpulse    147.0
Calories    329.3
Name: 10, dtype: float64)
(11, Duration     60.0
Pulse       100.0
Maxpulse    120.0
Calories    250.7
Name: 11, dtype: float64)
(12, Duration     60.0
Pulse       106.0
Maxpulse    128.0
Calories    345.3
Name: 12, dtype: float64)
(13, Duration     60.0
Pulse       104.0
Maxpulse    132.0
Calories    379.3
Name: 13, dtype: float64)
(14, Duration     60.0
Pulse        98.0
Maxpulse    123.0
Calories    275.0
Name: 14, dtype: float64)
(15, Duration     60.0
Pulse        98.0
Maxpulse    120.0
Calories    215.2
Name: 15, dtype: float64)
(16, Duration     60.0
Pulse       100.0
Maxpulse    120.0
Calories    300.0
Name: 16, dtype: float64)
(17, Duration     45.0
Pulse        90.0
Maxpulse    112.0
Calories      NaN
Name: 17, dtype: float64)
(18, Duration     60.0
Pulse       103.0
Maxpulse    123.0
Calories    323.0
Name: 18, dtype: float64)
(19, Duration     45.0
Pulse        97.0
Maxpulse    125.0
Calories    243.0
Name: 19, dtype: float64)
(20, Duration     60.0
Pulse       108.0
Maxpulse    131.0
Calories    364.2
Name: 20, dtype: float64)
(21, Duration     45.0
Pulse       100.0
Maxpulse    119.0
Calories    282.0
Name: 21, dtype: float64)
(22, Duration     60.0
Pulse       130.0
Maxpulse    101.0
Calories    300.0
Name: 22, dtype: float64)
(23, Duration     45.0
Pulse       105.0
Maxpulse    132.0
Calories    246.0
Name: 23, dtype: float64)
(24, Duration     60.0
Pulse       102.0
Maxpulse    126.0
Calories    334.5
Name: 24, dtype: float64)
(25, Duration     60.0
Pulse       100.0
Maxpulse    120.0
Calories    250.0
Name: 25, dtype: float64)
(26, Duration     60.0
Pulse        92.0
Maxpulse    118.0
Calories    241.0
Name: 26, dtype: float64)
(27, Duration     60.0
Pulse       103.0
Maxpulse    132.0
Calories      NaN
Name: 27, dtype: float64)
(28, Duration     60.0
Pulse       100.0
Maxpulse    132.0
Calories    280.0
Name: 28, dtype: float64)
(29, Duration     60.0
Pulse       102.0
Maxpulse    129.0
Calories    380.3
Name: 29, dtype: float64)
(30, Duration     60.0
Pulse        92.0
Maxpulse    115.0
Calories    243.0
Name: 30, dtype: float64)
(31, Duration     45.0
Pulse        90.0
Maxpulse    112.0
Calories    180.1
Name: 31, dtype: float64)
(32, Duration     60.0
Pulse       101.0
Maxpulse    124.0
Calories    299.0
Name: 32, dtype: float64)
(33, Duration     60.0
Pulse        93.0
Maxpulse    113.0
Calories    223.0
Name: 33, dtype: float64)
(34, Duration     60.0
Pulse       107.0
Maxpulse    136.0
Calories    361.0
Name: 34, dtype: float64)
(35, Duration     60.0
Pulse       114.0
Maxpulse    140.0
Calories    415.0
Name: 35, dtype: float64)
(36, Duration     60.0
Pulse       102.0
Maxpulse    127.0
Calories    300.0
Name: 36, dtype: float64)
(37, Duration     60.0
Pulse       100.0
Maxpulse    120.0
Calories    300.0
Name: 37, dtype: float64)
(38, Duration     60.0
Pulse       100.0
Maxpulse    120.0
Calories    300.0
Name: 38, dtype: float64)
(39, Duration     45.0
Pulse       104.0
Maxpulse    129.0
Calories    266.0
Name: 39, dtype: float64)
(40, Duration     45.0
Pulse        90.0
Maxpulse    112.0
Calories    180.1
Name: 40, dtype: float64)
(41, Duration     60.0
Pulse        98.0
Maxpulse    126.0
Calories    286.0
Name: 41, dtype: float64)
(42, Duration     60.0
Pulse       100.0
Maxpulse    122.0
Calories    329.4
Name: 42, dtype: float64)
(43, Duration     60.0
Pulse       111.0
Maxpulse    138.0
Calories    400.0
Name: 43, dtype: float64)
(44, Duration     60.0
Pulse       111.0
Maxpulse    131.0
Calories    397.0
Name: 44, dtype: float64)
(45, Duration     60.0
Pulse        99.0
Maxpulse    119.0
Calories    273.0
Name: 45, dtype: float64)
(46, Duration     60.0
Pulse       109.0
Maxpulse    153.0
Calories    387.6
Name: 46, dtype: float64)
(47, Duration     45.0
Pulse       111.0
Maxpulse    136.0
Calories    300.0
Name: 47, dtype: float64)
(48, Duration     45.0
Pulse       108.0
Maxpulse    129.0
Calories    298.0
Name: 48, dtype: float64)
(49, Duration     60.0
Pulse       111.0
Maxpulse    139.0
Calories    397.6
Name: 49, dtype: float64)
(50, Duration     60.0
Pulse       107.0
Maxpulse    136.0
Calories    380.2
Name: 50, dtype: float64)
(51, Duration     80.0
Pulse       123.0
Maxpulse    146.0
Calories    643.1
Name: 51, dtype: float64)
(52, Duration     60.0
Pulse       106.0
Maxpulse    130.0
Calories    263.0
Name: 52, dtype: float64)
(53, Duration     60.0
Pulse       118.0
Maxpulse    151.0
Calories    486.0
Name: 53, dtype: float64)
(54, Duration     30.0
Pulse       136.0
Maxpulse    175.0
Calories    238.0
Name: 54, dtype: float64)
(55, Duration     60.0
Pulse       121.0
Maxpulse    146.0
Calories    450.7
Name: 55, dtype: float64)
(56, Duration     60.0
Pulse       118.0
Maxpulse    121.0
Calories    413.0
Name: 56, dtype: float64)
(57, Duration     45.0
Pulse       115.0
Maxpulse    144.0
Calories    305.0
Name: 57, dtype: float64)
(58, Duration     20.0
Pulse       153.0
Maxpulse    172.0
Calories    226.4
Name: 58, dtype: float64)
(59, Duration     45.0
Pulse       123.0
Maxpulse    152.0
Calories    321.0
Name: 59, dtype: float64)
(60, Duration     210.0
Pulse        108.0
Maxpulse     160.0
Calories    1376.0
Name: 60, dtype: float64)
(61, Duration     160.0
Pulse        110.0
Maxpulse     137.0
Calories    1034.4
Name: 61, dtype: float64)
(62, Duration    160.0
Pulse       109.0
Maxpulse    135.0
Calories    853.0
Name: 62, dtype: float64)
(63, Duration     45.0
Pulse       118.0
Maxpulse    141.0
Calories    341.0
Name: 63, dtype: float64)
(64, Duration     20.0
Pulse       110.0
Maxpulse    130.0
Calories    131.4
Name: 64, dtype: float64)
(65, Duration    180.0
Pulse        90.0
Maxpulse    130.0
Calories    800.4
Name: 65, dtype: float64)
(66, Duration    150.0
Pulse       105.0
Maxpulse    135.0
Calories    873.4
Name: 66, dtype: float64)
(67, Duration    150.0
Pulse       107.0
Maxpulse    130.0
Calories    816.0
Name: 67, dtype: float64)
(68, Duration     20.0
Pulse       106.0
Maxpulse    136.0
Calories    110.4
Name: 68, dtype: float64)
(69, Duration     300.0
Pulse        108.0
Maxpulse     143.0
Calories    1500.2
Name: 69, dtype: float64)
(70, Duration     150.0
Pulse         97.0
Maxpulse     129.0
Calories    1115.0
Name: 70, dtype: float64)
(71, Duration     60.0
Pulse       109.0
Maxpulse    153.0
Calories    387.6
Name: 71, dtype: float64)
(72, Duration     90.0
Pulse       100.0
Maxpulse    127.0
Calories    700.0
Name: 72, dtype: float64)
(73, Duration    150.0
Pulse        97.0
Maxpulse    127.0
Calories    953.2
Name: 73, dtype: float64)
(74, Duration     45.0
Pulse       114.0
Maxpulse    146.0
Calories    304.0
Name: 74, dtype: float64)
(75, Duration     90.0
Pulse        98.0
Maxpulse    125.0
Calories    563.2
Name: 75, dtype: float64)
(76, Duration     45.0
Pulse       105.0
Maxpulse    134.0
Calories    251.0
Name: 76, dtype: float64)
(77, Duration     45.0
Pulse       110.0
Maxpulse    141.0
Calories    300.0
Name: 77, dtype: float64)
(78, Duration    120.0
Pulse       100.0
Maxpulse    130.0
Calories    500.4
Name: 78, dtype: float64)
(79, Duration     270.0
Pulse        100.0
Maxpulse     131.0
Calories    1729.0
Name: 79, dtype: float64)
(80, Duration     30.0
Pulse       159.0
Maxpulse    182.0
Calories    319.2
Name: 80, dtype: float64)
(81, Duration     45.0
Pulse       149.0
Maxpulse    169.0
Calories    344.0
Name: 81, dtype: float64)
(82, Duration     30.0
Pulse       103.0
Maxpulse    139.0
Calories    151.1
Name: 82, dtype: float64)
(83, Duration    120.0
Pulse       100.0
Maxpulse    130.0
Calories    500.0
Name: 83, dtype: float64)
(84, Duration     45.0
Pulse       100.0
Maxpulse    120.0
Calories    225.3
Name: 84, dtype: float64)
(85, Duration     30.0
Pulse       151.0
Maxpulse    170.0
Calories    300.0
Name: 85, dtype: float64)
(86, Duration     45.0
Pulse       102.0
Maxpulse    136.0
Calories    234.0
Name: 86, dtype: float64)
(87, Duration     120.0
Pulse        100.0
Maxpulse     157.0
Calories    1000.1
Name: 87, dtype: float64)
(88, Duration     45.0
Pulse       129.0
Maxpulse    103.0
Calories    242.0
Name: 88, dtype: float64)
(89, Duration     20.0
Pulse        83.0
Maxpulse    107.0
Calories     50.3
Name: 89, dtype: float64)
(90, Duration    180.0
Pulse       101.0
Maxpulse    127.0
Calories    600.1
Name: 90, dtype: float64)
(91, Duration     45.0
Pulse       107.0
Maxpulse    137.0
Calories      NaN
Name: 91, dtype: float64)
(92, Duration     30.0
Pulse        90.0
Maxpulse    107.0
Calories    105.3
Name: 92, dtype: float64)
(93, Duration     15.0
Pulse        80.0
Maxpulse    100.0
Calories     50.5
Name: 93, dtype: float64)
(94, Duration     20.0
Pulse       150.0
Maxpulse    171.0
Calories    127.4
Name: 94, dtype: float64)
(95, Duration     20.0
Pulse       151.0
Maxpulse    168.0
Calories    229.4
Name: 95, dtype: float64)
(96, Duration     30.0
Pulse        95.0
Maxpulse    128.0
Calories    128.2
Name: 96, dtype: float64)
(97, Duration     25.0
Pulse       152.0
Maxpulse    168.0
Calories    244.2
Name: 97, dtype: float64)
(98, Duration     30.0
Pulse       109.0
Maxpulse    131.0
Calories    188.2
Name: 98, dtype: float64)
(99, Duration     90.0
Pulse        93.0
Maxpulse    124.0
Calories    604.1
Name: 99, dtype: float64)
(100, Duration     20.0
Pulse        95.0
Maxpulse    112.0
Calories     77.7
Name: 100, dtype: float64)
(101, Duration     90.0
Pulse        90.0
Maxpulse    110.0
Calories    500.0
Name: 101, dtype: float64)
(102, Duration     90.0
Pulse        90.0
Maxpulse    100.0
Calories    500.0
Name: 102, dtype: float64)
(103, Duration     90.0
Pulse        90.0
Maxpulse    100.0
Calories    500.4
Name: 103, dtype: float64)
(104, Duration     30.0
Pulse        92.0
Maxpulse    108.0
Calories     92.7
Name: 104, dtype: float64)
(105, Duration     30.0
Pulse        93.0
Maxpulse    128.0
Calories    124.0
Name: 105, dtype: float64)
(106, Duration    180.0
Pulse        90.0
Maxpulse    120.0
Calories    800.3
Name: 106, dtype: float64)
(107, Duration     30.0
Pulse        90.0
Maxpulse    120.0
Calories     86.2
Name: 107, dtype: float64)
(108, Duration     90.0
Pulse        90.0
Maxpulse    120.0
Calories    500.3
Name: 108, dtype: float64)
(109, Duration     210.0
Pulse        137.0
Maxpulse     184.0
Calories    1860.4
Name: 109, dtype: float64)
(110, Duration     60.0
Pulse       102.0
Maxpulse    124.0
Calories    325.2
Name: 110, dtype: float64)
(111, Duration     45.0
Pulse       107.0
Maxpulse    124.0
Calories    275.0
Name: 111, dtype: float64)
(112, Duration     15.0
Pulse       124.0
Maxpulse    139.0
Calories    124.2
Name: 112, dtype: float64)
(113, Duration     45.0
Pulse       100.0
Maxpulse    120.0
Calories    225.3
Name: 113, dtype: float64)
(114, Duration     60.0
Pulse       108.0
Maxpulse    131.0
Calories    367.6
Name: 114, dtype: float64)
(115, Duration     60.0
Pulse       108.0
Maxpulse    151.0
Calories    351.7
Name: 115, dtype: float64)
(116, Duration     60.0
Pulse       116.0
Maxpulse    141.0
Calories    443.0
Name: 116, dtype: float64)
(117, Duration     60.0
Pulse        97.0
Maxpulse    122.0
Calories    277.4
Name: 117, dtype: float64)
(118, Duration     60.0
Pulse       105.0
Maxpulse    125.0
Calories      NaN
Name: 118, dtype: float64)
(119, Duration     60.0
Pulse       103.0
Maxpulse    124.0
Calories    332.7
Name: 119, dtype: float64)
(120, Duration     30.0
Pulse       112.0
Maxpulse    137.0
Calories    193.9
Name: 120, dtype: float64)
(121, Duration     45.0
Pulse       100.0
Maxpulse    120.0
Calories    100.7
Name: 121, dtype: float64)
(122, Duration     60.0
Pulse       119.0
Maxpulse    169.0
Calories    336.7
Name: 122, dtype: float64)
(123, Duration     60.0
Pulse       107.0
Maxpulse    127.0
Calories    344.9
Name: 123, dtype: float64)
(124, Duration     60.0
Pulse       111.0
Maxpulse    151.0
Calories    368.5
Name: 124, dtype: float64)
(125, Duration     60.0
Pulse        98.0
Maxpulse    122.0
Calories    271.0
Name: 125, dtype: float64)
(126, Duration     60.0
Pulse        97.0
Maxpulse    124.0
Calories    275.3
Name: 126, dtype: float64)
(127, Duration     60.0
Pulse       109.0
Maxpulse    127.0
Calories    382.0
Name: 127, dtype: float64)
(128, Duration     90.0
Pulse        99.0
Maxpulse    125.0
Calories    466.4
Name: 128, dtype: float64)
(129, Duration     60.0
Pulse       114.0
Maxpulse    151.0
Calories    384.0
Name: 129, dtype: float64)
(130, Duration     60.0
Pulse       104.0
Maxpulse    134.0
Calories    342.5
Name: 130, dtype: float64)
(131, Duration     60.0
Pulse       107.0
Maxpulse    138.0
Calories    357.5
Name: 131, dtype: float64)
(132, Duration     60.0
Pulse       103.0
Maxpulse    133.0
Calories    335.0
Name: 132, dtype: float64)
(133, Duration     60.0
Pulse       106.0
Maxpulse    132.0
Calories    327.5
Name: 133, dtype: float64)
(134, Duration     60.0
Pulse       103.0
Maxpulse    136.0
Calories    339.0
Name: 134, dtype: float64)
(135, Duration     20.0
Pulse       136.0
Maxpulse    156.0
Calories    189.0
Name: 135, dtype: float64)
(136, Duration     45.0
Pulse       117.0
Maxpulse    143.0
Calories    317.7
Name: 136, dtype: float64)
(137, Duration     45.0
Pulse       115.0
Maxpulse    137.0
Calories    318.0
Name: 137, dtype: float64)
(138, Duration     45.0
Pulse       113.0
Maxpulse    138.0
Calories    308.0
Name: 138, dtype: float64)
(139, Duration     20.0
Pulse       141.0
Maxpulse    162.0
Calories    222.4
Name: 139, dtype: float64)
(140, Duration     60.0
Pulse       108.0
Maxpulse    135.0
Calories    390.0
Name: 140, dtype: float64)
(141, Duration     60.0
Pulse        97.0
Maxpulse    127.0
Calories      NaN
Name: 141, dtype: float64)
(142, Duration     45.0
Pulse       100.0
Maxpulse    120.0
Calories    250.4
Name: 142, dtype: float64)
(143, Duration     45.0
Pulse       122.0
Maxpulse    149.0
Calories    335.4
Name: 143, dtype: float64)
(144, Duration     60.0
Pulse       136.0
Maxpulse    170.0
Calories    470.2
Name: 144, dtype: float64)
(145, Duration     45.0
Pulse       106.0
Maxpulse    126.0
Calories    270.8
Name: 145, dtype: float64)
(146, Duration     60.0
Pulse       107.0
Maxpulse    136.0
Calories    400.0
Name: 146, dtype: float64)
(147, Duration     60.0
Pulse       112.0
Maxpulse    146.0
Calories    361.9
Name: 147, dtype: float64)
(148, Duration     30.0
Pulse       103.0
Maxpulse    127.0
Calories    185.0
Name: 148, dtype: float64)
(149, Duration     60.0
Pulse       110.0
Maxpulse    150.0
Calories    409.4
Name: 149, dtype: float64)
(150, Duration     60.0
Pulse       106.0
Maxpulse    134.0
Calories    343.0
Name: 150, dtype: float64)
(151, Duration     60.0
Pulse       109.0
Maxpulse    129.0
Calories    353.2
Name: 151, dtype: float64)
(152, Duration     60.0
Pulse       109.0
Maxpulse    138.0
Calories    374.0
Name: 152, dtype: float64)
(153, Duration     30.0
Pulse       150.0
Maxpulse    167.0
Calories    275.8
Name: 153, dtype: float64)
(154, Duration     60.0
Pulse       105.0
Maxpulse    128.0
Calories    328.0
Name: 154, dtype: float64)
(155, Duration     60.0
Pulse       111.0
Maxpulse    151.0
Calories    368.5
Name: 155, dtype: float64)
(156, Duration     60.0
Pulse        97.0
Maxpulse    131.0
Calories    270.4
Name: 156, dtype: float64)
(157, Duration     60.0
Pulse       100.0
Maxpulse    120.0
Calories    270.4
Name: 157, dtype: float64)
(158, Duration     60.0
Pulse       114.0
Maxpulse    150.0
Calories    382.8
Name: 158, dtype: float64)
(159, Duration     30.0
Pulse        80.0
Maxpulse    120.0
Calories    240.9
Name: 159, dtype: float64)
(160, Duration     30.0
Pulse        85.0
Maxpulse    120.0
Calories    250.4
Name: 160, dtype: float64)
(161, Duration     45.0
Pulse        90.0
Maxpulse    130.0
Calories    260.4
Name: 161, dtype: float64)
(162, Duration     45.0
Pulse        95.0
Maxpulse    130.0
Calories    270.0
Name: 162, dtype: float64)
(163, Duration     45.0
Pulse       100.0
Maxpulse    140.0
Calories    280.9
Name: 163, dtype: float64)
(164, Duration     60.0
Pulse       105.0
Maxpulse    140.0
Calories    290.8
Name: 164, dtype: float64)
(165, Duration     60.0
Pulse       110.0
Maxpulse    145.0
Calories    300.0
Name: 165, dtype: float64)
(166, Duration     60.0
Pulse       115.0
Maxpulse    145.0
Calories    310.2
Name: 166, dtype: float64)
(167, Duration     75.0
Pulse       120.0
Maxpulse    150.0
Calories    320.4
Name: 167, dtype: float64)
(168, Duration     75.0
Pulse       125.0
Maxpulse    150.0
Calories    330.4
Name: 168, dtype: float64)

In [38]:
set(df['Duration'])

{15, 20, 25, 30, 45, 60, 75, 80, 90, 120, 150, 160, 180, 210, 270, 300}